# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7943b9beef2c2974a4097d3a3e3dc4ac75df5a410114c2e4f118d9a12addf9b0c82ef691722d1387c2fceba110174910d2afed5f14733ae6b12780631fe7a9

test:
  secret_key_base: 9d0958af00123c5a96b44f815eefb6bcf584a9003356b910161201d421367267606185c3a37f07af4201faea34636261d8d9f7ae1c1fc60a5a81a0ec3ace2c03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
